### ISSUE TITLE
Editor not rendering preview

### ISSUE THREAD

**Issue by Smando87** [icewind1991/files_markdown#62] opened 2017-09-12 13:12 UTC
Hi, in a fresh install of Nextcloud the editor do not rendering preview

Nextcloud 12.0.2
Markdown Editor 2.0.0

Javascript error in the browser's console:

```
Uncaught TypeError: Cannot read property 'renderText' of undefined
    at Object.<anonymous> (editor.js?v=4096575305f6fb2e82271139d78b51bf-0:1)
    at Object.<anonymous> (core.js?v=4096575305f6fb2e82271139d78b51bf-0:817)
    at later (core.js?v=4096575305f6fb2e82271139d78b51bf-0:841)
```

**Comment by guzzard** [comment] 2017-09-12 13:55
@Smando87 open the console before logging into Nextcloud, and check if you get the same errors in the log as issue #58.

**Comment by icewind1991** [comment] 2017-09-14 12:07
Most likely a duplicate of #58

**Closed by icewind1991** 2017-09-14 12:07 UTC

**Comment by geiseri** [comment] 2017-09-22 22:19
This is not as it it still broken in Chrome for windows.  I see the following console message:
```
editor.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:1 Uncaught (in promise) TypeError: Cannot read property 'renderText' of undefined
    at editor.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:1
    at <anonymous>
(anonymous) @ editor.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:1
Async Call
(anonymous) @ editor.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:1
(anonymous) @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:817
later @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:841
setTimeout (async)
(anonymous) @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:852
(anonymous) @ merged.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:319
(anonymous) @ merged.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:570
j @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:2
fireWith @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:2
x @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:4
(anonymous) @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:4
XMLHttpRequest.send (async)
send @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:4
ajax @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:4
n.(anonymous function) @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:4
loadFile @ merged.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:559
loadEditor @ merged.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:293
_onEditorTrigger @ merged.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:193
_onClickFile @ merged-index.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:4650
dispatch @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:3
r.handle @ core.js?v=d28859f1fe063b346e0a12ac2a9ea3e6-0:3
```
