### ISSUE TITLE
Live preview not working in Chromium

### ISSUE THREAD

**Issue by guzzard** [icewind1991/files_markdown#60] opened 2017-09-10 10:30 UTC
Nextcloud 11.0.4
Text editor 2.2
Markdown editor 2.0.0
Chromium 61.0.3163.79

![screenshot-area-2017-09-10-122451](https://user-images.githubusercontent.com/9007314/30248208-b8cffe58-9623-11e7-95e9-c53109230a4c.png)

**Comment by guzzard** [comment] 2017-09-10 11:19
![screenshot-area-2017-09-10-131527](https://user-images.githubusercontent.com/9007314/30248566-7defd4c8-962a-11e7-916c-6bfcd1044951.png)

More errors on new login. Seems like same issue as #58.

**Comment by guzzard** [comment] 2017-09-10 11:29
Preview works fine in Firefox, but this warning can be seen in the console "Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead."

**Comment by icewind1991** [comment] 2017-09-11 15:12
Duplicate of https://github.com/icewind1991/files_markdown/issues/58

Pleasae have a look at my questions in that issue to try and debug this issue

**Closed by icewind1991** 2017-09-11 15:12 UTC
