### ISSUE TITLE
Long lines are cut i.e. not wrapped

### ISSUE THREAD

**Issue by js-d-coder** [icewind1991/files_markdown#102] opened 2018-09-10 17:54 UTC
I am using Nextcloud 13 and this app version  2.0.4 on Firefox 63.
As you can notice that all of the sentence is not visible in editor (left side), because it is getting 'cut' instead of wrapping properly.  

![screenshot from 2018-09-10 23 18 36](https://user-images.githubusercontent.com/23054879/45314873-8ea52980-b550-11e8-8f91-cf13eb1eb368.jpeg)

Thanks for you app, very helpful!

**Comment by laurens94** [comment] 2018-09-20 11:13
This is a duplicate of issue #78

**Comment by icewind1991** [comment] 2018-11-27 10:08
Closing as duplicate of #78

**Closed by icewind1991** 2018-11-27 10:08 UTC
