### ISSUE TITLE
Modified since opening errors

### ISSUE THREAD

**Issue by NiTRoeSE** [icewind1991/files_markdown#34] opened 2017-01-06 23:36 UTC
Hi, i installed the app in nextcloud 11 with the App Store.
The app seems to run fine but, if i type in some text the app safes every 10 seconds the document and every safe produces one error entry in the logfile:

> Error	files_texteditor	File: /test.md modified since opening.	2017-01-06T22:23:25+0100
> Error	files_texteditor	File: /test.md modified since opening.	2017-01-06T22:23:25+0100
> Error	files_texteditor	File: /test.md modified since opening.	2017-01-06T22:23:24+0100
> Error	files_texteditor	File: /test.md modified since opening.	2017-01-06T22:23:24+0100

**Comment by girst** [comment] 2017-01-09 23:27
I experience the same.

This also affects the files_texteditor; a bug report has been submitted to here: https://github.com/nextcloud/files_texteditor/issues/23

**Comment by icewind1991** [comment] 2017-01-10 15:46
Closing this here since it's caused by the texteditor, not this app

**Closed by icewind1991** 2017-01-10 15:46 UTC
