### ISSUE TITLE
Scrolling is broken

### ISSUE THREAD

**Issue by artemanufrij** [icewind1991/files_markdown#57] opened 2017-09-04 20:15 UTC
after last update scrolling looks like broken.

1. open large .md file
2. scroll down (on the right side)
3. try to scroll up -> doesn't work in my case

tested on Epiphany and Chromium

**Comment by artemanufrij** [comment] 2017-09-05 10:14
Right now I tested scrolling behavior on IE11. Same issue

**Comment by Isvvc** [comment] 2017-09-06 16:55
For me, it seems it's trying to automatically scroll the right pane with the left, but the right pane is much longer, so I can't scroll past the lowest point on the left pane.

It seems to be an issue with an autoscroll feature added.

**Comment by Isvvc** [comment] 2017-09-08 05:16
This is making this markdown editor almost unusable for me. Reverting it back to how it was without any attempted autoscroll would be great if that would be simple.

**Comment by icewind1991** [comment] 2017-09-08 12:03
Can you send me the problematic markdown file, the synchronized scrolling *should* correctly handle difference in length between source and preview

**Comment by Isvvc** [comment] 2017-09-08 16:52
It seems to behave differently each time I open a document, so no specific file is causing issues. The issues seemed to be strongly exaggerated when I first tried to open a document after the update, so it is usable for me now.

The only consistent issues I can find are 
  when I open a document and scroll all the way down on the right pane, it tries to jump up to the level of the left pane, but then will scroll down again if you make it, and
  opening a document where the right pane has a scroll bar and the left doesn't it will always jump to the top on the right pane.

**Comment by artemanufrij** [comment] 2017-09-08 17:07
@icewind1991 

don't forget to rename it
[ArchLinux.md.txt](https://github.com/icewind1991/files_markdown/files/1288607/ArchLinux.md.txt)

**Comment by icewind1991** [comment] 2017-09-10 16:49
Thanks, could reproduce the problem with the file, fix should be released in the coming week

**Comment by icewind1991** [comment] 2017-09-14 12:08
This should be fixed with 2.0.1

**Closed by icewind1991** 2017-09-14 12:08 UTC
