### ISSUE TITLE
Do not have split screens

### ISSUE THREAD

**Issue by itisco** [icewind1991/files_markdown#134] opened 2019-09-19 12:20 UTC
Hello
I installed your app on my nextcloud 16 and do not have the split screen as displayed on the screen capture of your exemples.
Why is that?
Here is what I have
![Screenshot_2019-09-19 test md - Nextcloud](https://user-images.githubusercontent.com/4580313/65243339-744d4680-dae8-11e9-9fb4-dc3e283f67e5.png)
I do not have any errors in the console log of firefox.
I created an .MD file through the Add new text document of Nextcloud.
Thaks for your help.

**Comment by wintaeh** [comment] 2019-09-22 15:10
That is because you have installed another text editor with formatting capabilities. Right click on the file an open it with the right one. Then you will have the split screen view and markdown functionality.

**Comment by unijoy** [comment] 2019-10-24 03:18
some issue .and there is no item about markdown after right click the file

**Comment by unijoy** [comment] 2019-10-24 05:11
> some issue .and there is no item about markdown after right click the file

finally i got it works:

1:you need to install "files_texteditor-17.0.0" (i had downloaded it and copy into custom_apps folder
2:disable official text editor and enable plain text editor , files_mardown enable to.

**Comment by hellolgml** [comment] 2019-11-21 09:37
@unijoy 
how can you find "files_texteditor-17.0.0" ？

**Comment by Franky1** [comment] 2020-03-04 12:15
this is a duplicate of #135

**Comment by fds2610** [comment] 2020-09-10 08:37
This is NOT duplicate from #135 !
plain text editor does not install anymore !

**Comment by icewind1991** [comment] 2020-09-10 20:31
You can find the text editor here: https://apps.nextcloud.com/apps/files_texteditor

**Closed by icewind1991** 2020-09-10 20:31 UTC
