### ISSUE TITLE
About Chinese issue

### ISSUE THREAD

**Issue by xujwoo** [icewind1991/files_markdown#48] opened 2017-05-20 08:35 UTC
When I use the input method to enter the Chinese language will appear when the problem of dislocation, and hit the space bar can not be selected to enter the Chinese.

**Comment by Acris** [comment] 2017-06-19 15:22
+1

**Comment by Acris** [comment] 2017-06-30 08:11
See: https://github.com/nextcloud/notes/issues/59#issuecomment-312204569

**Comment by icewind1991** [comment] 2017-07-12 14:46
This is a duplicate of https://github.com/nextcloud/files_texteditor/issues/44, this app only provides the md preview

**Closed by icewind1991** 2017-07-12 14:46 UTC
