### ISSUE TITLE
text editor + preview window

### ISSUE THREAD

**Issue by mmeinesz** [icewind1991/files_markdown#136] opened 2019-11-05 09:23 UTC
I used to have a text editor on a left side window and a preview on a right side window. Now there is only a "Wysiwig" view/edit window. Is this a new version of files_markdown? It does not work well for me, especially when you want to create markdown tables.

**Comment by robot144** [comment] 2019-11-14 13:08
I have the same issue. My guess is that the new text editor (https://github.com/nextcloud/text), that is part of the nextcloud release, is started instead of this plugin. I have not found a workaround yet. I like the 2 pane style much better.

**Comment by noe-spi** [comment] 2019-11-27 11:30
Same is with me - the markdown editor is overruled by text editor. Even if I temporarily deactivate the text editor the markdown editor doesn't open but the download window appear.

Onyone who knows how to solve that issue?

**Comment by E1k3** [comment] 2019-12-01 17:28
This happens, because the plain text editor is no longer available in the Nextcloud Plugin Store and this markdown editor depends on it.

If you disable the "Text" app, install the [plain text editor](https://github.com/nextcloud/files_texteditor) manually and enable both the plain text editor and the markdown editor, you should have what you want.

Nextclouds decision to focus on the new Text app and discontinue the development of the old plain text editor is a bad move in my decision. There is an [issue about this on their Github repo](https://github.com/nextcloud/files_texteditor/issues/185).

**Comment by noe-spi** [comment] 2019-12-01 20:18
...thanks a lot for sharing this info - I'll try it as you described.

**Comment by noe-spi** [comment] 2019-12-01 20:27
... very interesting. I'm running Nextcloud 17 as a docker container. When I try to install my machine says:
This app can't be installed because the following dependencies are not fulfilled: Server version 18 or higher is needed 
;-(

**Comment by E1k3** [comment] 2019-12-02 00:41
Yes, this is mentioned in the linked issue. You have to modify the appinfo/info.xml file to have a valid min version (eg 17).

The app should be fully compatible, ghey just chose to set an invalid min version.

**Comment by noe-spi** [comment] 2019-12-02 18:27
Perfect, now everything is working - thank you very much helping me!

**Comment by raelb** [comment] 2019-12-06 10:16
I am running NextCloud v16, and also having this issue. I have disabled the apps `Text` and `Text Editor`. I installed/enabled `Markdown Editor`. I see `files_texteditor` under the `apps` directory, however I could not see how to "enable" this plugin. In the apps listing I could not see an entry for this "plain text editor".

How to enable the "plain text editor" or what is it called in the apps listing?
Perhaps I need to uninstall the Text and Text Editor applications?
Thanks

**Comment by E1k3** [comment] 2019-12-06 10:30
"TextEditor" should be what you need to enable alongside the Markdown Editor.

**Comment by raelb** [comment] 2019-12-06 10:36
Thanks. All good now.

**Comment by DJCrashdummy** [comment] 2020-02-18 08:58
i guess this is a duplicate of #135.

**Comment by fthommen** [comment] 2020-04-07 18:43
This all seems to be a slightly hacky way to get the Markdown Editor up and going.  I love(d) the Markdown Editor but I am running an productive NextCloud 18.x instance for an whole institute and I'd prefer to keep it clean (i.e. no hacks, no apps from outside the app store).  Hence my question to the developer: Are there plans to provide fixes to the Markdown Editor app (e.g. automatically include all dependencies in the Markdown Editor itself) or is - in the long run - the manual installation of the Text Editor the only way to be able to use the Markdown Editor.

**Comment by ifuchs** [comment] 2020-04-13 00:35
Installed the Plain Text Editor manually but still cannot preview window of Markdown editor to work. WIth Plain text Editor enabled, I can't edit .md files at all.

**Comment by icewind1991** [comment] 2020-04-16 14:42
It's very unlikely that this app will pull in files_texteditor, instead the plan is to publish the old texteditor to the appstore (https://github.com/nextcloud/files_texteditor/pull/192)

**Comment by fthommen** [comment] 2020-04-16 15:24
> It's very unlikely that this app will pull in files_texteditor, instead the plan is to publish the old texteditor to the appstore ([nextcloud/files_texteditor#192](https://github.com/nextcloud/files_texteditor/pull/192))

even better.  Thanks.  I am looking forward to it

**Comment by fthommen** [comment] 2020-07-26 18:38
As far as I can see, in the meantime the "Plaintext Editor" App is again available (at least as of NC 18.0.7), so this issue can probably be closed.

**Closed** 2020-08-26 14:49 UTC
