### ISSUE TITLE
Text editor loses connection regularly

### ISSUE THREAD

**Issue by JordanDIG** [icewind1991/files_markdown#187] opened 2022-02-23 14:19 UTC
Nextcloud version: 23.0.2
Operating system and version: Raspbian

I am using Apache2
PHP version: 8.0

The issue you are facing: If I edit markdown documents via the embedded web texteditor, it loses regularly the sync:

file could not be loaded. Please check your internet connection (retry)

This occurs right after a few minutes and I guess a tip faster if you are on a edit.
This error occurs on different internet connections.

Steps to replicate it:

Open Files app on your cloud webinterface
Click a textfile to edit
Start writing to the opened file and wait till the above poppup message appears
Click rety and note, that nothing will reload. So reload the whole page

**Comment by malicioustoker** [comment] 2022-03-23 21:57
I have this same issue running on my Asustor NAS

**Comment by kousu** [comment] 2023-01-28 02:43
I am seeing this too but I'm not sure what the cause is. I've put what debugging I've done so far in https://help.nextcloud.com/t/text-editor-loses-connection-regularly/96787/5.

**Comment by dbolton** [comment] 2024-02-01 04:22
Likely fixed by https://github.com/nextcloud/text/pull/5126

**Closed** 2024-02-01 13:47 UTC
